/**
 * The announcements repository layout.
 *
 * ```
 * <repo>/
 * ├─ content/                     SOURCE OF TRUTH — never read by a client
 * │  ├─ announcements/<id>.json   one file per record: readable diffs, mergeable
 * │  ├─ media/<id>.<ext>          image originals, full resolution
 * │  ├─ retired-ids.json          ids that have ever existed and been deleted
 * │  └─ state.json                the monotonic revision counter
 * ├─ dist/                        BUILT — the only thing a client reads
 * │  ├─ announcements.json
 * │  └─ images/<id>-<hash8>.webp
 * └─ schema/announcements.v1.md   the contract, for whoever finds this repo
 * ```
 *
 * Two halves, and the split is the point. `content/` holds drafts, archived
 * records and audit dates; putting it in git is what gives the Manager backup,
 * history and a second machine for free. `dist/` is a pure projection of it,
 * regenerated by the build and never hand-edited.
 *
 * Originals are kept because throwing away the source of an encoded image is
 * irreversible — you will want to re-encode when the budget changes, or re-crop.
 */

import { join } from 'node:path';

export interface RepoPaths {
  root: string;
  content: string;
  announcements: string;
  media: string;
  retiredIds: string;
  state: string;
  dist: string;
  manifest: string;
  images: string;
  schemaDoc: string;
}

export function repoPaths(root: string): RepoPaths {
  const content = join(root, 'content');
  const dist = join(root, 'dist');

  return {
    root,
    content,
    announcements: join(content, 'announcements'),
    media: join(content, 'media'),
    retiredIds: join(content, 'retired-ids.json'),
    state: join(content, 'state.json'),
    dist,
    manifest: join(dist, 'announcements.json'),
    images: join(dist, 'images'),
    schemaDoc: join(root, 'schema', 'announcements.v1.md'),
  };
}

/** `<repo>/content/announcements/<id>.json` */
export function recordPath(paths: RepoPaths, id: string): string {
  return join(paths.announcements, `${id}.json`);
}

/**
 * The published image name: `images/<id>-<first 8 of the sha256>.webp`.
 *
 * Content-addressed, so an image is never mutated — only replaced by a
 * differently-named file. That answers cache invalidation and old-image
 * cleanup at once, and it is why the client can cache an image for ever.
 */
export function imageName(id: string, sha256: string): string {
  return `${id}-${sha256.slice(0, 8)}.webp`;
}

/** The value stored in `image.path`, always forward-slashed. */
export function imageManifestPath(id: string, sha256: string): string {
  return `images/${imageName(id, sha256)}`;
}
