/**
 * The announcements repository layout.
 *
 * ```
 * <repo>/
 * ├─ content/                     SOURCE OF TRUTH — never read by a client
 * │  ├─ announcements/<id>.json   one file per record: readable diffs, mergeable
 * │  ├─ media/<id>.<ext>          image originals, full resolution
 * │  ├─ retired-ids.json          ids that have ever existed and been deleted
 * │  └─ state.json                the monotonic revision counter
 * ├─ dist/                        BUILT — the only thing a client reads
 * │  ├─ announcements.json
 * │  └─ images/<id>-<hash8>.webp
 * └─ schema/announcements.v1.md   the contract, for whoever finds this repo
 * ```
 *
 * Two halves, and the split is the point. `content/` holds drafts, archived
 * records and audit dates; putting it in git is what gives the Manager backup,
 * history and a second machine for free. `dist/` is a pure projection of it,
 * regenerated by the build and never hand-edited.
 *
 * Originals are kept because throwing away the source of an encoded image is
 * irreversible — you will want to re-encode when the budget changes, or re-crop.
 */

import { join } from 'node:path';

import {
  ANNOUNCEMENTS_DIR,
  CONTENT_DIR,
  DIST_DIR,
  MEDIA_DIR,
  RETIRED_IDS_FILE,
  STATE_FILE,
} from '@ruood/announcement-authoring';

/**
 * A repository-relative path, as an absolute one.
 *
 * The relative names live in `@ruood/announcement-authoring` because the phone
 * addresses the same files over the GitHub API and cannot import `node:path`.
 * Composing them here rather than repeating the strings is what keeps "a record
 * is content/announcements/<id>.json" a single fact.
 */
function under(root: string, relative: string): string {
  return join(root, ...relative.split('/'));
}

export interface RepoPaths {
  root: string;
  content: string;
  announcements: string;
  media: string;
  retiredIds: string;
  state: string;
  dist: string;
  manifest: string;
  images: string;
  schemaDoc: string;
}

export function repoPaths(root: string): RepoPaths {
  const content = under(root, CONTENT_DIR);
  const dist = under(root, DIST_DIR);

  return {
    root,
    content,
    announcements: under(root, ANNOUNCEMENTS_DIR),
    media: under(root, MEDIA_DIR),
    retiredIds: under(root, RETIRED_IDS_FILE),
    state: under(root, STATE_FILE),
    dist,
    manifest: join(dist, 'announcements.json'),
    images: join(dist, 'images'),
    schemaDoc: join(root, 'schema', 'announcements.v1.md'),
  };
}

/** `<repo>/content/announcements/<id>.json` */
export function recordPath(paths: RepoPaths, id: string): string {
  return join(paths.announcements, `${id}.json`);
}

/**
 * The published image name: `images/<id>-<first 8 of the sha256>.webp`.
 *
 * Content-addressed, so an image is never mutated — only replaced by a
 * differently-named file. That answers cache invalidation and old-image
 * cleanup at once, and it is why the client can cache an image for ever.
 */
export function imageName(id: string, sha256: string): string {
  return `${id}-${sha256.slice(0, 8)}.webp`;
}

/** The value stored in `image.path`, always forward-slashed. */
export function imageManifestPath(id: string, sha256: string): string {
  return `images/${imageName(id, sha256)}`;
}

/**
 * The two publication channels.
 *
 * `staging` is a second manifest in the SAME repository, published by its own
 * commit to `dist/staging/`. A dev or TestFlight build is compiled with the
 * staging URL and sees it; a store build never does.
 *
 * Same repository rather than a branch or a second repo, because everything
 * that makes publishing safe here comes from there being one working copy: one
 * remote, one set of credentials, one `git log` that is the whole publication
 * history, and one `content/` that both channels project from.
 */
export const CHANNELS = ['production', 'staging'] as const;
export type Channel = (typeof CHANNELS)[number];

export function isChannel(value: unknown): value is Channel {
  return typeof value === 'string' && (CHANNELS as readonly string[]).includes(value);
}

export interface ChannelPaths {
  channel: Channel;
  dist: string;
  manifest: string;
  images: string;
  /**
   * What a publish to this channel stages, relative to the repository root.
   *
   * Explicit, and per-channel, for the same reason `commitPaths` takes paths
   * rather than `add -A`: staging the whole of `dist/` would make a production
   * publish sweep up whatever staging happened to have written, and the two are
   * meant to be able to differ.
   *
   * `keys/` is in both. It holds only the PUBLIC key record, and a signed
   * manifest whose public key was never committed is one CI cannot check and a
   * reader cannot trace — so it travels with the first publish rather than
   * waiting for someone to remember.
   */
  commitPaths: string[];
}

export function channelPaths(paths: RepoPaths, channel: Channel = 'production'): ChannelPaths {
  if (channel === 'staging') {
    const dist = join(paths.dist, 'staging');
    return {
      channel,
      dist,
      manifest: join(dist, 'announcements.json'),
      images: join(dist, 'images'),
      commitPaths: ['dist/staging', 'content', 'keys'],
    };
  }

  return {
    channel,
    dist: paths.dist,
    manifest: paths.manifest,
    images: paths.images,
    // Named individually rather than as `dist`, so `dist/staging` is untouched.
    commitPaths: ['dist/announcements.json', 'dist/images', 'content', 'keys'],
  };
}
